# this wil initialize the configuration types in the configuration storage
commerce_multisafepay.settings:
  type: commerce_payment_gateway_configuration
  mapping:
    test_api_key:
      type: string
      label: 'Test API Key'
    live_api_key:
      type: string
      label: 'Live API Key'
    accout_type:
      type: string
      label: 'Account Type'
    seconds_active:
      type: string
      label: 'Seconds Alive'
