version: 2
jobs:
  codesniffer:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          name: Install Drupal Code sniffer
          command: composer global require drupal/coder
      - run:
          name: Run Drupal Code sniffer
          command: |
            /home/circleci/.composer/vendor/bin/phpcs \
              --standard=/home/circleci/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml \
              -n \
              /var/www/html
workflows:
  version: 2
  default_check:
    jobs:
      - codesniffer
